name: coinstalker
description: Cryptocurrency exchange rate tracker

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  validate: ^1.7.0
  google_sign_in: ^3.2.2
  firebase_auth: ^0.6.2+1

  http: ^0.11.3+17
  json_annotation: ^1.0.0

  cloud_firestore: ^0.8.2+1

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^0.10.0
  json_serializable: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - images/email.png
    - images/google.png
    - images/facebook.png
    - images/twitter.png
    - images/stock.jpg
